// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Oc_oBvS2LZkUMrEUaRrFQi50S84EHTA',
    appId: '1:966805984725:web:86a4c96a977a87695d195c',
    messagingSenderId: '966805984725',
    projectId: 'kavin-market-app',
    authDomain: 'kavin-market-app.firebaseapp.com',
    storageBucket: 'kavin-market-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIPyKadyMYdeiYZW-E9iRun3MR0iDQTfg',
    appId: '1:966805984725:android:1ebb3bb11c1fa1725d195c',
    messagingSenderId: '966805984725',
    projectId: 'kavin-market-app',
    storageBucket: 'kavin-market-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGvmhYsWJVXVnlKVyJbLr8O1WH7a2shAY',
    appId: '1:966805984725:ios:b9925190387d28945d195c',
    messagingSenderId: '966805984725',
    projectId: 'kavin-market-app',
    storageBucket: 'kavin-market-app.appspot.com',
    iosClientId: '966805984725-ulb7ce5hgu90mhghkbc150pg2sf21j26.apps.googleusercontent.com',
    iosBundleId: 'com.example.kavinMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGvmhYsWJVXVnlKVyJbLr8O1WH7a2shAY',
    appId: '1:966805984725:ios:b9925190387d28945d195c',
    messagingSenderId: '966805984725',
    projectId: 'kavin-market-app',
    storageBucket: 'kavin-market-app.appspot.com',
    iosClientId: '966805984725-ulb7ce5hgu90mhghkbc150pg2sf21j26.apps.googleusercontent.com',
    iosBundleId: 'com.example.kavinMart',
  );
}
